apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cicero-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "3deed24f-dd46-4f2d-ae6e-2f11200fc741"
    keyvaultName: "kv-mercury-prod"
    tenantId: "078fd273-e372-4513-8eee-0342373ac232"
    objects: |
      array:
        - |
          objectName: cicero-db-user
          objectType: secret
        - |
          objectName: cicero-db-password
          objectType: secret
        - |
          objectName: storage-account-name
          objectType: secret
        - |
          objectName: cicero-blob-sas
          objectType: secret
        - |
          objectName: cicero-telegram-bot-token
          objectType: secret
        - |
          objectName: cicero-telegram-chat-id
          objectType: secret
  secretObjects:
    - secretName: cicero-db-credentials
      type: kubernetes.io/basic-auth
      data:
        - objectName: cicero-db-user
          key: username
        - objectName: cicero-db-password
          key: password
    - secretName: cicero-n8n-env
      type: Opaque
      data:
        - objectName: cicero-db-user
          key: DB_POSTGRESDB_USER
        - objectName: cicero-db-password
          key: DB_POSTGRESDB_PASSWORD
    - secretName: cicero-backup-creds
      type: Opaque
      data:
        - objectName: storage-account-name
          key: storage-account-name
        - objectName: cicero-blob-sas
          key: cicero-blob-sas
    - secretName: cicero-telegram-creds
      type: Opaque
      data:
        - objectName: cicero-telegram-bot-token
          key: TELEGRAM_BOT_TOKEN
        - objectName: cicero-telegram-chat-id
          key: TELEGRAM_CHAT_ID
