apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: brutus-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "3caca64d-1523-4521-aa90-51d0f72674b5"
    keyvaultName: "kv-mercury-staging"
    tenantId: "078fd273-e372-4513-8eee-0342373ac232"
    objects: |
      array:
        - |
          objectName: brutus-db-user
          objectType: secret
        - |
          objectName: brutus-db-password
          objectType: secret
        - |
          objectName: storage-account-name
          objectType: secret
        - |
          objectName: brutus-blob-sas
          objectType: secret
        - |
          objectName: brutus-telegram-bot-token
          objectType: secret
        - |
          objectName: brutus-telegram-chat-id
          objectType: secret
  secretObjects:
    - secretName: brutus-db-credentials
      type: kubernetes.io/basic-auth
      data:
        - objectName: brutus-db-user
          key: username
        - objectName: brutus-db-password
          key: password
    - secretName: brutus-n8n-env
      type: Opaque
      data:
        - objectName: brutus-db-user
          key: DB_POSTGRESDB_USER
        - objectName: brutus-db-password
          key: DB_POSTGRESDB_PASSWORD
    - secretName: brutus-backup-creds
      type: Opaque
      data:
        - objectName: storage-account-name
          key: storage-account-name
        - objectName: brutus-blob-sas
          key: brutus-blob-sas
    - secretName: brutus-telegram-creds
      type: Opaque
      data:
        - objectName: brutus-telegram-bot-token
          key: TELEGRAM_BOT_TOKEN
        - objectName: brutus-telegram-chat-id
          key: TELEGRAM_CHAT_ID
